# Generated by Django 5.0.3 on 2024-03-31 12:02

import continent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continentName', models.CharField(max_length=50, validators=[continent.models.validate_continent_name])),
            ],
        ),
    ]
