# Generated by Django 5.0.3 on 2024-03-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUpInOut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darazuser',
            name='confirm_password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='darazuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='darazuser',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
