# Generated by Django 5.0.3 on 2024-03-31 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('continent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50)),
                ('continentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='continent.continent')),
            ],
            options={
                'ordering': ['countryName'],
            },
        ),
    ]
